version: "3.9"
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "testDb"
      POSTGRES_USER: "testDbUser"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432"
  app:
    image: prod-service:local
    container_name: task_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres